### ISSUE TITLE
How to use Readme?

### ISSUE THREAD

**Issue by ansjin** [resin-io-modules/resin-compose-parse#40]
Could you please tell me how this package can be used as there is no details inside the Readme

**Comment by dfunckt** [comment]
@ansjin apologies for the lack of documentation.

In a nutshell, you load up the compose file, convert it to a JS object via with a yaml-to-js converter and pass the object to `compose-parse.normalize()` -- that'll make sure to validate the input and return a [normalised composition](https://github.com/resin-io-modules/resin-compose-parse/blob/master/src/types.ts#L181-L185). Then you pass the composition to `compose-parse.parse()` to get back a list of [image descriptors](https://github.com/resin-io-modules/resin-compose-parse/blob/master/src/types.ts#L196-L199) that you can use to build or pull the images defined in the compose file.

You can use this code as a basis: https://github.com/resin-io/resin-cli/blob/master/lib/utils/compose.coffee#L50-L73

**Comment by ansjin** [comment]
@dfunckt Thank you so much for the information and quick reply!
